services:

  backend:
    build: .
    container_name: hallodoc-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma_db:/app/chroma_db
      - ./data/medicines:/app/medicines
    extra_hosts:
      - "host.docker.internal:host-gateway"
  chromadb:
    image: chromadb/chroma:latest
    container_name: chroma-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - ./data/chroma_db:/app/chroma_db
